# SPDX-FileCopyrightText: 2020 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# SPDX-License-Identifier: MIT

name: COPR

on:
  push:
    branches:
      - develop

jobs:
  copr:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild package
        run: curl -X POST ${{ secrets.COPR_WEBHOOK_URL }}