# SPDX-FileCopyrightText: 2022 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: Translations Sync

on:
  schedule:
    - cron: '0 0 * * *'
  repository_dispatch:
    types:
      - transifex

jobs:
  update-translations:
    uses: lirios/.github/.github/workflows/transifex.yml@master
    secrets:
      TX_TOKEN: ${{ secrets.TX_TOKEN }}
      CI_SSH_KEY: ${{ secrets.CI_SSH_KEY }}
